services:
  api:
    build:
      context: .
      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
      DATABASE_URL: mysql://root:password@db/mydatabase
    ports:
      - '80:8000'
    restart: "no"
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-database
    ports:
      - "3306:3306"  # Porta per il database MySQL
    environment:
      MYSQL_ROOT_USER: root                
      MYSQL_ROOT_PASSWORD: rootpassword  # Password per l'utente root
      MYSQL_DATABASE: mydatabase        # Nome del database predefinito     
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"  # Porta per phpMyAdmin
    environment:
      PMA_HOST: db         
      MYSQL_ROOT_USER: root                
      MYSQL_ROOT_PASSWORD: rootpassword    # Password dell'utente root per phpMyAdmin
    restart: always